### ISSUE TITLE
Please add description and topics

### ISSUE THREAD

**Issue by ufechner7** [lthUniBonn/AWERA#9]
Please add a description and topics for the github project. It makes it easier to find.

Suggested topics (keyword):
- wind energy
- wind resources
- airborne wind energy

**Comment by lthUniBonn** [comment]
Great suggestion as a starting point for improving the useability. Thank you, Uwe - great that you checked AWERA out right after the conference!
I'll get to this first thing on Monday.

**Comment by lthUniBonn** [comment]
Done.
